export const canvasStyles = {
  background: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: '1',
      pointerEvents: 'auto',
    },
  },
  subtitle: {
    container: {
      position: 'relative',
      backgroundColor: 'rgba(25, 24, 35, 0.82)',
      backdropFilter: 'blur(18px)',
      padding: '14px 48px 14px 24px',
      borderRadius: '18px',
      border: '1px solid rgba(255, 220, 235, 0.22)',
      boxShadow: '0 16px 44px rgba(35, 20, 35, 0.22)',
      minWidth: '60%',
      maxWidth: '95%',
    },
    closeButton: {
      position: 'absolute',
      right: '8px',
      top: '8px',
      minWidth: '28px',
      width: '28px',
      height: '28px',
      borderRadius: 'full',
      color: 'rgba(255,255,255,.68)',
      background: 'transparent',
      _hover: { color: 'white', background: 'rgba(255,182,210,.18)' },
    },
    text: {
      color: 'white',
      fontSize: '1.05rem',
      textAlign: 'center',
      lineHeight: '1.4',
      whiteSpace: 'pre-wrap',
    },
  },
  wsStatus: {
    container: {
      position: 'relative',
      // top: '20px',
      // left: '20px',
      zIndex: 2,
      height: '24px',
      minWidth: '112px',
      width: '112px',
      padding: '0 10px',
      borderRadius: '999px',
      fontSize: '12px',
      fontWeight: 'medium',
      color: 'white',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      whiteSpace: 'nowrap',
      border: '1px solid rgba(255,255,255,0.14)',
      boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.12)',
      _hover: {
        opacity: 0.8,
      },
    },
  },
};
